services:
  postgres:
    image: postgres:17-alpine
    container_name: swarm-evaluator-postgres
    environment:
      POSTGRES_DB: swarm_evaluator
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d swarm_evaluator"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:
    driver: local