name: Build and deploy

on:
  push:
    branches:
      - cicd
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: |
      !contains(github.event.head_commit.message, 'skip build')
    permissions: write-all
    runs-on: ubicloud-standard-16
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare build
        run: |
          echo "SANITIZED_REF=$(echo "${GITHUB_REF##*/}" | tr '/' '-' | tr -d '.')" >> $GITHUB_ENV

      - id: commit
        uses: prompt/actions-commit-hash@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./evaluator
          push: true
          file: evaluator/Dockerfile
          tags: |
            ghcr.io/renlabs-dev/prediction-swarm-evaluator:${{ steps.commit.outputs.short }}
            ghcr.io/renlabs-dev/prediction-swarm-evaluator:${{ env.SANITIZED_REF }}

  # clean-stale:
  #   runs-on: ubicloud-standard-2
  #   container:
  #     image: ghcr.io/renlabs-dev/devops-ci:latest

  #   env:
  #     VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
  #     VAULT_ROLE_ID: ${{ secrets.VAULT_ROLE_ID }}
  #     VAULT_SECRET_ID: ${{ secrets.VAULT_SECRET_ID }}

  #   steps:
  #     - name: Setup Kubernetes authentication
  #       run: /apps/k8s_auth_w_approle_sa.sh

  #     - name: Clean stale releases
  #       run: |
  #         /apps/clean_stale_releases.sh torus-prod-prediction-swarm
